//Generated by AI
export function isValidLatitude(lat: string): boolean {
    const latitude = parseFloat(lat);
    return !isNaN(latitude) && latitude >= -90 && latitude <= 90;
}

export function isValidLongitude(lon: string): boolean {
    const longitude = parseFloat(lon);
    return !isNaN(longitude) && longitude >= -180 && longitude <= 180;
}